"""initial PostgreSQL 18 schema

Revision ID: 67ca7ce29628
Revises:
Create Date: 2026-08-28 20:24:30.746946
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "67ca7ce29628"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token_prefix", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index("ix_api_tokens_prefix", "api_tokens", ["token_prefix"], unique=False)
    op.create_table(
        "groups",
        sa.Column("legacy_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("color", sa.String(length=16), server_default="#64748b", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("system_key", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("level BETWEEN 1 AND 3", name=op.f("ck_groups_level_range")),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["groups.id"], name=op.f("fk_groups_parent_id_groups"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_groups_legacy_id")),
        sa.UniqueConstraint("name", name=op.f("uq_groups_name")),
        sa.UniqueConstraint("system_key", name=op.f("uq_groups_system_key")),
    )
    op.create_index("ix_groups_parent_sort", "groups", ["parent_id", "sort_order"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_type", sa.String(length=96), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("total_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("succeeded_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skipped_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','pausing','paused','cancelling',"
            "'cancelled','completed','partial','failed')",
            name=op.f("ck_jobs_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index("ix_jobs_status_priority", "jobs", ["status", "priority", "created_at"], unique=False)
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=16), server_default="#64748b", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "accounts",
        sa.Column("legacy_id", sa.BigInteger(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("account_type", sa.String(length=32), server_default="outlook", nullable=False),
        sa.Column("provider", sa.String(length=32), server_default="outlook", nullable=False),
        sa.Column("authorization_type", sa.String(length=32), server_default="", nullable=False),
        sa.Column("lifecycle_status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("authorization_status", sa.String(length=32), server_default="unknown", nullable=False),
        sa.Column("token_status", sa.String(length=32), server_default="never", nullable=False),
        sa.Column("mail_health_status", sa.String(length=32), server_default="unknown", nullable=False),
        sa.Column(
            "proxy_health_status", sa.String(length=32), server_default="not_configured", nullable=False
        ),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("remark", sa.Text(), server_default="", nullable=False),
        sa.Column("last_token_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_mail_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_mail_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_reason_code", sa.String(length=96), nullable=True),
        sa.Column("health_error_summary", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "authorization_status IN ('unknown','pending','valid','invalid','reauthorization_required')",
            name=op.f("ck_accounts_authorization_status_values"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('active','inactive','archived')",
            name=op.f("ck_accounts_lifecycle_status_values"),
        ),
        sa.CheckConstraint(
            "mail_health_status IN ('unknown','checking','healthy','degraded','failed')",
            name=op.f("ck_accounts_mail_health_status_values"),
        ),
        sa.CheckConstraint(
            "proxy_health_status IN ('not_configured','unknown','healthy','failed')",
            name=op.f("ck_accounts_proxy_health_status_values"),
        ),
        sa.CheckConstraint(
            "token_status IN ('never','checking','success','failed','stale')",
            name=op.f("ck_accounts_token_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_accounts_group_id_groups"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("email_normalized", name=op.f("uq_accounts_email_normalized")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_accounts_legacy_id")),
    )
    op.create_index("ix_accounts_group_created", "accounts", ["group_id", "created_at"], unique=False)
    op.create_index("ix_accounts_health", "accounts", ["mail_health_status", "token_status"], unique=False)
    op.create_index("ix_accounts_lifecycle", "accounts", ["lifecycle_status"], unique=False)
    op.create_table(
        "job_items",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("item_key", sa.String(length=200), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=96), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','leased','running','retry_wait','succeeded',"
            "'failed','skipped','cancelled')",
            name=op.f("ck_job_items_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_items_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_items")),
        sa.UniqueConstraint("job_id", "item_key", name=op.f("uq_job_items_job_id")),
    )
    op.create_index("ix_job_items_job_status", "job_items", ["job_id", "status"], unique=False)
    op.create_index(
        "ix_job_items_lease", "job_items", ["status", "run_after", "lease_expires_at"], unique=False
    )
    op.create_table(
        "account_aliases",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_aliases_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_aliases")),
        sa.UniqueConstraint("email_normalized", name=op.f("uq_account_aliases_email_normalized")),
    )
    op.create_table(
        "account_health_snapshots",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=32), server_default="metadata", nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=True),
        sa.Column("reason_code", sa.String(length=96), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_health_snapshots_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_health_snapshots")),
    )
    op.create_index(
        "ix_health_snapshots_account_checked",
        "account_health_snapshots",
        ["account_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "account_secrets",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("password_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("imap_password_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_secrets_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("pk_account_secrets")),
    )
    op.create_table(
        "account_tags",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_tags_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_account_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("account_id", "tag_id", name=op.f("pk_account_tags")),
    )
    op.create_table(
        "job_events",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("job_item_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), server_default="info", nullable=False),
        sa.Column("message", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["job_item_id"],
            ["job_items.id"],
            name=op.f("fk_job_events_job_item_id_job_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_job_events")),
    )
    op.create_index("ix_job_events_job_sequence", "job_events", ["job_id", "sequence"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_events_job_sequence", table_name="job_events")
    op.drop_table("job_events")
    op.drop_table("account_tags")
    op.drop_table("account_secrets")
    op.drop_index("ix_health_snapshots_account_checked", table_name="account_health_snapshots")
    op.drop_table("account_health_snapshots")
    op.drop_table("account_aliases")
    op.drop_index("ix_job_items_lease", table_name="job_items")
    op.drop_index("ix_job_items_job_status", table_name="job_items")
    op.drop_table("job_items")
    op.drop_index("ix_accounts_lifecycle", table_name="accounts")
    op.drop_index("ix_accounts_health", table_name="accounts")
    op.drop_index("ix_accounts_group_created", table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("tags")
    op.drop_index("ix_jobs_status_priority", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_groups_parent_sort", table_name="groups")
    op.drop_table("groups")
    op.drop_index("ix_api_tokens_prefix", table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
