"""add encrypted proxy profiles

Revision ID: cb9d5e0f1f0f
Revises: 22da3649e282
Create Date: 2026-08-28 21:29:02.559502
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cb9d5e0f1f0f"
down_revision: str | Sequence[str] | None = "22da3649e282"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxy_profiles",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("primary_url_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("fallback_url_1_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("fallback_url_2_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxy_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_proxy_profiles_name")),
    )
    op.add_column("accounts", sa.Column("proxy_profile_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_accounts_proxy_profile_id_proxy_profiles"),
        "accounts",
        "proxy_profiles",
        ["proxy_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("groups", sa.Column("proxy_profile_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_groups_proxy_profile_id_proxy_profiles"),
        "groups",
        "proxy_profiles",
        ["proxy_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_groups_proxy_profile_id_proxy_profiles"), "groups", type_="foreignkey")
    op.drop_column("groups", "proxy_profile_id")
    op.drop_constraint(op.f("fk_accounts_proxy_profile_id_proxy_profiles"), "accounts", type_="foreignkey")
    op.drop_column("accounts", "proxy_profile_id")
    op.drop_table("proxy_profiles")
    # ### end Alembic commands ###
