"""add import batches and account row version

Revision ID: cfa1cb5db0e8
Revises: 67ca7ce29628
Create Date: 2026-08-28 20:46:54.360048
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cfa1cb5db0e8"
down_revision: str | Sequence[str] | None = "67ca7ce29628"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("status", sa.String(length=32), server_default="validated", nullable=False),
        sa.Column("account_type", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("remark", sa.Text(), server_default="", nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("total_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("valid_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("invalid_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("conflict_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skipped_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('validated','committing','completed','partial','failed','rolled_back')",
            name=op.f("ck_import_batches_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_import_batches_group_id_groups"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_import_batches_idempotency_key")),
    )
    op.create_index(
        "ix_import_batches_status_created", "import_batches", ["status", "created_at"], unique=False
    )
    op.create_table(
        "import_batch_items",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("email_normalized", sa.String(length=320), nullable=True),
        sa.Column("account_type", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("remark", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("password_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("imap_password_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=96), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('valid','invalid','conflict','created','skipped','failed','rolled_back')",
            name=op.f("ck_import_batch_items_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_batch_items_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_account_id"],
            ["accounts.id"],
            name=op.f("fk_import_batch_items_created_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_import_batch_items_group_id_groups"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batch_items")),
        sa.UniqueConstraint("batch_id", "line_number", name=op.f("uq_import_batch_items_batch_id")),
    )
    op.create_index(
        "ix_import_batch_items_batch_status", "import_batch_items", ["batch_id", "status"], unique=False
    )
    op.add_column("accounts", sa.Column("row_version", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "row_version")
    op.drop_index("ix_import_batch_items_batch_status", table_name="import_batch_items")
    op.drop_table("import_batch_items")
    op.drop_index("ix_import_batches_status_created", table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
